DATABASE My_Catalog

CREATE TABLE source (
  id INTEGER NOT NULL,
  name VARCHAR(100) NOT NULL,
  items ARRAY(VARCHAR(100)) NOT NULL,
  PRIMARY KEY (id)
)

CREATE TABLE label (
  id INTEGER NOT NULL,
  title VARCHAR(100) NOT NULL,
  color VARCHAR(100) NOT NULL,
  items ARRAY(VARCHAR(100)) NOT NULL,
  PRIMARY KEY (id)
)

